name: Rust

on:
  push:
    branches: [ master, update-ci ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install dependencies
      env: 
        ACCEPT_EULA: Y
      run:  |
            rustup override set nightly && \
            sudo -E apt-get update && \
            # sudo -E dpkg --configure -a && \
            # sudo -E dpkg --remove containers-common && \
            # sudo -E apt-get upgrade -y && \
            sudo -E apt-get install -y zlib1g-dev apt-utils && \
            sudo -E apt-get install -y opt libedit-dev build-essential make && \
            sudo -E apt-get install -y cmake llvm-10 pkg-config jq && \
            sudo -E apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev && \
            cd vicis_ir && \
            cargo install cargo-kcov && \
            cargo kcov --print-install-kcov-sh | sh
    - name: Run tests
      run: cd vicis_ir && cargo test --verbose
    - name: Run kcov vicis_ir
      working-directory: ./vicis_ir
      run: |
            cargo test; \
            bash ../.github/kcov.sh
    - name: Run kcov vicis_codegen
      working-directory: ./vicis_codegen
      run: |
            cargo test; \
            bash ../.github/kcov.sh
    - name: Run kcov vicis_interpreter
      working-directory: ./vicis_interpreter
      run: |
            cargo test; \
            bash ../.github/kcov.sh
